### ISSUE TITLE
Using Quill with requireJS?

### ISSUE THREAD

**Issue by radiart** [KillerCodeMonkey/ngQuill#18]
Hi I'm trying to use Quill with requireJS? But all the time I have error:

````
Quill is not defined
```

What I'm doing wrong?

```
require.config({
 paths: {
        'quill': '../lib/quill/dist/quill.min',
        'ngQuill': '../lib/ngquill/src/ng-quill'
},
    shim: {
        'quill': {
          'deps': ['angular'],
          'exports':'Quill'
        },
        'ngQuill' :  ['quill']
    }
});
```

**Comment by KillerCodeMonkey** [comment]
Heyho, i am using my directive in requirejs context. But you need to modify
the directive a little bit. Modify the ng-quill.js:

1. wrap the directive in define function
2. load quill AS dependency.

The Problem is, that if you are using quill it tries to put the Quill
object on the window Object (so you can access them via Quill). In
requirejs Quill is not set on the window object. You can try to load
quill.js not with requirejs.
Am 18.08.2015 15:02 schrieb "Rafał Radomski" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
@radiart 
please keep me up to date for your open quilljs issue:
https://github.com/quilljs/quill/issues/455

if there are news or i have to change something, to make it requirejs (or other amds) compatible, let me know.

**Comment by KillerCodeMonkey** [comment]
UMD wrapper should do it:

```
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(factory);
  } else if (typeof exports === 'object') {
    module.exports = factory;
  } else {
    root.MYMODULE = factory();
  }
})(this, function () {
  // code
});
```

**Comment by KillerCodeMonkey** [comment]
added umd wrapper with grunt-umd in v1.5.1

**Comment by miguelbaldi** [comment]
I'm still not able to use ng-quill with requirejs. Could you provide some sample code?

**Comment by KillerCodeMonkey** [comment]
@miguelbaldi 
will look into it later and inform you about any updates + requirejs example

**Comment by KillerCodeMonkey** [comment]
@miguelbaldi try to use latest release (2.2.2)

And look here for a working demo
https://github.com/KillerCodeMonkey/ng-quill/blob/gh-pages/demo-amd.html

**Comment by miguelbaldi** [comment]
@KillerCodeMonkey link throws a 404 error.
I will try version 2.2.2. Thank you!

**Comment by KillerCodeMonkey** [comment]
yeah i removed the gh-pages branch --> i fixed the link

**Comment by miguelbaldi** [comment]
@KillerCodeMonkey Version 2.2.2 works like a charm. Thank you!
