### ISSUE TITLE
Angular2 Version

### ISSUE THREAD

**Issue by maku** [KillerCodeMonkey/ngQuill#39]
Is a version for Angular2 planned?

**Comment by KillerCodeMonkey** [comment]
It is planned but i am unsure if i schould wait till quill 1.0 is released and then how to handle both version -> 1 repo for both or better splitted in two repos.

What do you think?

**Comment by maku** [comment]
Don't know exactly how far quill 1.0. is away (when I look at the quill page it seems it is far away). 
So this could last a long time. From my point of view there is no good reason to wait :-) (apart from missing time)

Personally I would prefer two repos... (But I  don't know if there is much code to share from ngQuill).

BTW, it seems the guys from https://github.com/primefaces/primeng have an ng2 editor based on quill...

**Comment by KillerCodeMonkey** [comment]
Hey there. You could share some parts --> i could rewrite the whole thing in typescript ^^.

Yeah it seems they have done it. But I develop things, because i want to learn with it the technology and solving problems on my own. 

So i do not search the whole time for a thing that nobody developed, yet --> because that is hard to find ;).

And i am so happy, that so many people are using and contributing my little ngquill-module :+1: 

It sounds like a little weekend project. The primefaces implemented it a little bit to strict in the angular 2 context i think. So they are listening on the Angular 2 Routing events. But many people are hoping there is a final uiRoute for ng2.

I have to think about it :).

**Comment by maku** [comment]
Don't think the primeface impl. listen to route events. It is a simple component without dependencies to any route specific. But I would not use the primeface component because I don't want the other primeng stuff...

Nevertheless, it is a good idea to implement the new stuff in typescript (which I really like). Looking forward... :-)

**Comment by KillerCodeMonkey** [comment]
I close the issue, because i will do it if i have the time.
